[project]
name = "iterator-workflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.1",
    "langchain-community>=0.3.29",
    "langchain-groq>=0.3.7",
    "langgraph>=0.6.6",
    "uvicorn>=0.35.0",
]
